name: Input Credit Card No
on: 
 workflow_dispatch:
   inputs:
    cardno: 
      description: 'Enter Credit Card No'
      required: true
      default: '123456789012345'
    cardtype:
      description: 'Choose Card Type'
      required: true
      type: choice
      options:
       - master
       - visa
       - amex
      default: master 
jobs:
 validate-length:
  runs-on: ubuntu-latest
  steps:
   - name: Check Credit Card Number Of Digits
     run: |
       cardNo="${{github.event.inputs.cardno}}" 
       len=${#cardNo}
       echo "Length:$len"
       if [ $len -lt 10 ]; then
         echo "Card No is invalid"
       else
         echo "Card No is Valid"
       fi   
 shows-inputs:
   runs-on: ubuntu-latest
   steps:
    - name: Print the input values
      run: |
       echo "Card No: ${{github.event.inputs.cardno}}"
       echo "Card Type ${{github.event.inputs.cardtype}}"
      
 
